"""fix_foreign_keys_and_booleans

Revision ID: 176977ce3821
Revises: 
Create Date: 2026-05-15 17:27:32.367991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '176977ce3821'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('target_type', sa.Enum('digital_human', 'video', 'script', 'image'), nullable=False, comment='审核对象类型'),
    sa.Column('target_id', sa.BigInteger(), nullable=False, comment='审核对象ID'),
    sa.Column('review_type', sa.Enum('auto', 'manual'), nullable=False, comment='审核类型'),
    sa.Column('risk_score', sa.Float(), nullable=True, comment='风险分数 0-1'),
    sa.Column('risk_labels', sa.JSON(), nullable=True, comment='风险标签列表'),
    sa.Column('submit_data', sa.JSON(), nullable=True, comment='提交的原始数据'),
    sa.Column('result', sa.Enum('pending', 'approved', 'rejected'), nullable=False, comment='审核结果'),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True, comment='审核员ID'),
    sa.Column('review_comment', sa.String(length=500), nullable=True, comment='审核备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'content_reviews', ['created_at'], unique=False)
    op.create_index('idx_result', 'content_reviews', ['result'], unique=False)
    op.create_index('idx_target', 'content_reviews', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_user_id', 'content_reviews', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_writing_tasks', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_writing_tasks', 'script_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.alter_column('digital_humans', 'is_default',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否为默认数字人',
               existing_nullable=True)
    op.alter_column('generation_tasks', 'is_timeout',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否超时',
               existing_nullable=True)
    op.create_foreign_key(None, 'generation_tasks', 'video_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('scripts', 'is_template',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否为模板',
               existing_nullable=True)
    op.alter_column('scripts', 'ai_generated',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否AI生成',
               existing_nullable=True)
    op.create_foreign_key(None, 'scripts', 'script_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'scripts', 'voice_clones', ['voice_id'], ['id'], ondelete='SET NULL')
    op.alter_column('system_configs', 'is_public',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否公开',
               existing_nullable=True)
    op.alter_column('system_configs', 'is_editable',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否可编辑',
               existing_nullable=True)
    op.create_foreign_key(None, 'tts_audio_files', 'scripts', ['script_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tts_audio_files', 'generation_tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tts_audio_files', 'voice_clones', ['voice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tts_audio_files', 'video_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_coupons', 'coupons', ['coupon_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_devices', 'is_active',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否活跃',
               existing_nullable=True)
    op.alter_column('user_login_histories', 'is_abnormal',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否异常登录',
               existing_nullable=True)
    op.alter_column('user_memberships', 'auto_renew',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否自动续费',
               existing_nullable=True)
    op.create_foreign_key(None, 'user_memberships', 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_messages', 'is_read',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否已读',
               existing_nullable=True)
    op.alter_column('user_messages', 'push_sent',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否已推送',
               existing_nullable=True)
    op.alter_column('user_messages', 'email_sent',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否已发送邮件',
               existing_nullable=True)
    op.alter_column('user_messages', 'sms_sent',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否已发送短信',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_task_complete',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='任务完成通知',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_task_failed',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='任务失败通知',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_review_result',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='审核结果通知',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_system',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='系统公告通知',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_enabled',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='邮件通知总开关',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_task_complete',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='任务完成(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_task_failed',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='任务失败(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_payment',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='支付相关(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_security',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='安全相关(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'sms_enabled',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='短信通知总开关',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'sms_payment',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='支付相关(短信)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'sms_security',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='安全相关(短信)',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               comment='密码哈希（手机注册用户可为空）',
               existing_comment='密码哈希')
    op.alter_column('users', 'real_name_verified',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='实名认证状态',
               existing_nullable=True)
    op.alter_column('video_outputs', 'has_audio',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否有音频',
               existing_nullable=True)
    op.alter_column('video_outputs', 'watermark_embedded',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否嵌入水印',
               existing_nullable=True)
    op.alter_column('video_outputs', 'share_enabled',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否启用分享',
               existing_nullable=True)
    op.create_foreign_key(None, 'video_outputs', 'video_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'video_projects', 'scripts', ['script_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'video_projects', 'digital_humans', ['digital_human_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'video_projects', 'user_assets', ['bgm_asset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'video_projects', 'voice_clones', ['voice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'video_projects', 'user_assets', ['background_asset_id'], ['id'], ondelete='SET NULL')
    op.alter_column('voice_clones', 'is_default',
               existing_type=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               type_=sa.Boolean(),
               existing_comment='是否为默认音色',
               existing_nullable=True)
    op.create_foreign_key(None, 'voice_clones', 'digital_humans', ['digital_human_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_clones', type_='foreignkey')
    op.alter_column('voice_clones', 'is_default',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否为默认音色',
               existing_nullable=True)
    op.drop_constraint(None, 'video_projects', type_='foreignkey')
    op.drop_constraint(None, 'video_projects', type_='foreignkey')
    op.drop_constraint(None, 'video_projects', type_='foreignkey')
    op.drop_constraint(None, 'video_projects', type_='foreignkey')
    op.drop_constraint(None, 'video_projects', type_='foreignkey')
    op.drop_constraint(None, 'video_outputs', type_='foreignkey')
    op.alter_column('video_outputs', 'share_enabled',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否启用分享',
               existing_nullable=True)
    op.alter_column('video_outputs', 'watermark_embedded',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否嵌入水印',
               existing_nullable=True)
    op.alter_column('video_outputs', 'has_audio',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否有音频',
               existing_nullable=True)
    op.alter_column('users', 'real_name_verified',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='实名认证状态',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               comment='密码哈希',
               existing_comment='密码哈希（手机注册用户可为空）')
    op.alter_column('user_notification_settings', 'sms_security',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='安全相关(短信)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'sms_payment',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='支付相关(短信)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'sms_enabled',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='短信通知总开关',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_security',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='安全相关(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_payment',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='支付相关(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_task_failed',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='任务失败(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_task_complete',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='任务完成(邮件)',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'email_enabled',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='邮件通知总开关',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_system',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='系统公告通知',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_review_result',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='审核结果通知',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_task_failed',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='任务失败通知',
               existing_nullable=True)
    op.alter_column('user_notification_settings', 'notify_task_complete',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='任务完成通知',
               existing_nullable=True)
    op.alter_column('user_messages', 'sms_sent',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否已发送短信',
               existing_nullable=True)
    op.alter_column('user_messages', 'email_sent',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否已发送邮件',
               existing_nullable=True)
    op.alter_column('user_messages', 'push_sent',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否已推送',
               existing_nullable=True)
    op.alter_column('user_messages', 'is_read',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否已读',
               existing_nullable=True)
    op.drop_constraint(None, 'user_memberships', type_='foreignkey')
    op.alter_column('user_memberships', 'auto_renew',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否自动续费',
               existing_nullable=True)
    op.alter_column('user_login_histories', 'is_abnormal',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否异常登录',
               existing_nullable=True)
    op.alter_column('user_devices', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否活跃',
               existing_nullable=True)
    op.drop_constraint(None, 'user_coupons', type_='foreignkey')
    op.drop_constraint(None, 'tts_audio_files', type_='foreignkey')
    op.drop_constraint(None, 'tts_audio_files', type_='foreignkey')
    op.drop_constraint(None, 'tts_audio_files', type_='foreignkey')
    op.drop_constraint(None, 'tts_audio_files', type_='foreignkey')
    op.alter_column('system_configs', 'is_editable',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否可编辑',
               existing_nullable=True)
    op.alter_column('system_configs', 'is_public',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否公开',
               existing_nullable=True)
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.drop_constraint(None, 'scripts', type_='foreignkey')
    op.alter_column('scripts', 'ai_generated',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否AI生成',
               existing_nullable=True)
    op.alter_column('scripts', 'is_template',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否为模板',
               existing_nullable=True)
    op.drop_constraint(None, 'generation_tasks', type_='foreignkey')
    op.alter_column('generation_tasks', 'is_timeout',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否超时',
               existing_nullable=True)
    op.alter_column('digital_humans', 'is_default',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('0', '1', collation='utf8mb4_unicode_ci'),
               existing_comment='是否为默认数字人',
               existing_nullable=True)
    op.drop_constraint(None, 'ai_writing_tasks', type_='foreignkey')
    op.drop_constraint(None, 'ai_writing_tasks', type_='foreignkey')
    op.drop_index('idx_user_id', table_name='content_reviews')
    op.drop_index('idx_target', table_name='content_reviews')
    op.drop_index('idx_result', table_name='content_reviews')
    op.drop_index('idx_created_at', table_name='content_reviews')
    op.drop_table('content_reviews')
    # ### end Alembic commands ###
