"""initial

Revision ID: 1984090aaca1
Revises: 
Create Date: 2026-05-15 14:49:41.175892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1984090aaca1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='user_oauth_bindings')
    op.drop_table('user_oauth_bindings')
    op.drop_index('idx_stat_date', table_name='user_statistics')
    op.drop_index('idx_user_date', table_name='user_statistics')
    op.drop_table('user_statistics')
    op.drop_index('idx_digital_human_id', table_name='voice_clones')
    op.drop_index('idx_status', table_name='voice_clones')
    op.drop_index('idx_user_id', table_name='voice_clones')
    op.drop_table('voice_clones')
    op.drop_index('idx_created_at', table_name='video_projects')
    op.drop_index('idx_digital_human', table_name='video_projects')
    op.drop_index('idx_script', table_name='video_projects')
    op.drop_index('idx_status_time', table_name='video_projects')
    op.drop_index('idx_user_id', table_name='video_projects')
    op.drop_table('video_projects')
    op.drop_index('idx_date_hour', table_name='platform_statistics')
    op.drop_index('idx_stat_date', table_name='platform_statistics')
    op.drop_table('platform_statistics')
    op.drop_index('email', table_name='admins')
    op.drop_index('idx_role', table_name='admins')
    op.drop_index('idx_status', table_name='admins')
    op.drop_index('username', table_name='admins')
    op.drop_table('admins')
    op.drop_index('idx_level', table_name='asset_categories')
    op.drop_index('idx_parent', table_name='asset_categories')
    op.drop_index('idx_status', table_name='asset_categories')
    op.drop_table('asset_categories')
    op.drop_index('idx_script_id', table_name='ai_writing_tasks')
    op.drop_index('idx_status', table_name='ai_writing_tasks')
    op.drop_index('idx_user_id', table_name='ai_writing_tasks')
    op.drop_table('ai_writing_tasks')
    op.drop_index('idx_project_id', table_name='tts_audio_files')
    op.drop_index('idx_user_id', table_name='tts_audio_files')
    op.drop_index('idx_voice_id', table_name='tts_audio_files')
    op.drop_table('tts_audio_files')
    op.drop_index('idx_authorization', table_name='digital_humans')
    op.drop_index('idx_status', table_name='digital_humans')
    op.drop_index('idx_usage_count', table_name='digital_humans')
    op.drop_index('idx_user_id', table_name='digital_humans')
    op.drop_table('digital_humans')
    op.drop_index('idx_user_id', table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index('idx_category', table_name='user_assets')
    op.drop_index('idx_created_at', table_name='user_assets')
    op.drop_index('idx_status', table_name='user_assets')
    op.drop_index('idx_type', table_name='user_assets')
    op.drop_index('idx_user_id', table_name='user_assets')
    op.drop_table('user_assets')
    op.drop_index('idx_category', table_name='scripts')
    op.drop_index('idx_is_template', table_name='scripts')
    op.drop_index('idx_status', table_name='scripts')
    op.drop_index('idx_user_id', table_name='scripts')
    op.drop_table('scripts')
    op.drop_index('idx_transaction_no', table_name='user_wallet_transactions')
    op.drop_index('idx_type_time', table_name='user_wallet_transactions')
    op.drop_index('idx_user_id', table_name='user_wallet_transactions')
    op.drop_index('transaction_no', table_name='user_wallet_transactions')
    op.drop_table('user_wallet_transactions')
    op.drop_index('idx_category', table_name='script_templates')
    op.drop_index('idx_source', table_name='script_templates')
    op.drop_index('idx_status', table_name='script_templates')
    op.drop_index('idx_usage_count', table_name='script_templates')
    op.drop_table('script_templates')
    op.drop_index('coupon_code', table_name='user_coupons')
    op.drop_index('idx_coupon_id', table_name='user_coupons')
    op.drop_index('idx_status_time', table_name='user_coupons')
    op.drop_index('idx_user_id', table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index('idx_date_provider_model', table_name='model_usage_statistics')
    op.drop_index('idx_stat_date', table_name='model_usage_statistics')
    op.drop_table('model_usage_statistics')
    op.drop_index('idx_action', table_name='admin_operation_logs')
    op.drop_index('idx_admin_id', table_name='admin_operation_logs')
    op.drop_index('idx_created_at', table_name='admin_operation_logs')
    op.drop_index('idx_target', table_name='admin_operation_logs')
    op.drop_table('admin_operation_logs')
    op.drop_index('idx_category', table_name='platform_assets')
    op.drop_index('idx_license', table_name='platform_assets')
    op.drop_index('idx_status', table_name='platform_assets')
    op.drop_index('idx_type', table_name='platform_assets')
    op.drop_index('idx_usage_count', table_name='platform_assets')
    op.drop_table('platform_assets')
    op.drop_index('email', table_name='users')
    op.drop_index('idx_created_at', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_index('idx_membership', table_name='users')
    op.drop_index('idx_phone', table_name='users')
    op.drop_index('idx_status', table_name='users')
    op.drop_index('phone', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_created_at', table_name='user_login_histories')
    op.drop_index('idx_ip', table_name='user_login_histories')
    op.drop_index('idx_user_id', table_name='user_login_histories')
    op.drop_table('user_login_histories')
    op.drop_index('user_id', table_name='user_wallets')
    op.drop_table('user_wallets')
    op.drop_index('idx_batch_id', table_name='generation_tasks')
    op.drop_index('idx_created_at', table_name='generation_tasks')
    op.drop_index('idx_project_id', table_name='generation_tasks')
    op.drop_index('idx_status_priority', table_name='generation_tasks')
    op.drop_index('idx_user_id', table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index('idx_status', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index('idx_created_at', table_name='video_outputs')
    op.drop_index('idx_review_status', table_name='video_outputs')
    op.drop_index('project_id', table_name='video_outputs')
    op.drop_table('video_outputs')
    op.drop_index('idx_created_at', table_name='user_messages')
    op.drop_index('idx_type', table_name='user_messages')
    op.drop_index('idx_user_id_read', table_name='user_messages')
    op.drop_table('user_messages')
    op.drop_index('idx_end_at', table_name='user_memberships')
    op.drop_index('idx_order_no', table_name='user_memberships')
    op.drop_index('idx_status_time', table_name='user_memberships')
    op.drop_index('idx_user_id', table_name='user_memberships')
    op.drop_index('order_no', table_name='user_memberships')
    op.drop_table('user_memberships')
    op.drop_index('idx_user_id', table_name='user_notification_settings')
    op.drop_index('user_id', table_name='user_notification_settings')
    op.drop_table('user_notification_settings')
    op.drop_index('idx_created_at', table_name='digital_human_tasks')
    op.drop_index('idx_digital_human_id', table_name='digital_human_tasks')
    op.drop_index('idx_status', table_name='digital_human_tasks')
    op.drop_index('idx_user_id', table_name='digital_human_tasks')
    op.drop_table('digital_human_tasks')
    op.drop_index('config_key', table_name='system_configs')
    op.drop_index('idx_category', table_name='system_configs')
    op.drop_index('idx_is_public', table_name='system_configs')
    op.drop_table('system_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('config_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='配置值'),
    sa.Column('config_type', mysql.ENUM('string', 'number', 'boolean', 'json'), nullable=True, comment='配置类型'),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='描述'),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='分类'),
    sa.Column('is_public', mysql.ENUM('0', '1'), nullable=True, comment='是否公开'),
    sa.Column('is_editable', mysql.ENUM('0', '1'), nullable=True, comment='是否可编辑'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_is_public', 'system_configs', ['is_public'], unique=False)
    op.create_index('idx_category', 'system_configs', ['category'], unique=False)
    op.create_index('config_key', 'system_configs', ['config_key'], unique=False)
    op.create_table('digital_human_tasks',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('digital_human_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='数字人ID'),
    sa.Column('human_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='数字人名称'),
    sa.Column('task_type', mysql.ENUM('create', 'update', 'retrain'), nullable=False, comment='任务类型'),
    sa.Column('status', mysql.ENUM('queued', 'processing', 'completed', 'failed', 'cancelled'), nullable=True, comment='任务状态'),
    sa.Column('priority', mysql.BIGINT(), autoincrement=False, nullable=True, comment='优先级'),
    sa.Column('model_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='提供商'),
    sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='模型名称'),
    sa.Column('model_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='模型版本'),
    sa.Column('input_config', mysql.JSON(), nullable=False, comment='输入配置'),
    sa.Column('progress', mysql.BIGINT(), autoincrement=False, nullable=True, comment='进度 0-100'),
    sa.Column('current_step', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='当前步骤'),
    sa.Column('output_config', mysql.JSON(), nullable=True, comment='输出结果'),
    sa.Column('model_file_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='模型文件URL'),
    sa.Column('preview_image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='预览图URL'),
    sa.Column('preview_video_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='预览视频URL'),
    sa.Column('started_at', mysql.DATETIME(), nullable=True, comment='开始处理时间'),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True, comment='完成时间'),
    sa.Column('duration_seconds', mysql.BIGINT(), autoincrement=False, nullable=True, comment='处理耗时(秒)'),
    sa.Column('cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='成本(分)'),
    sa.Column('error_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='错误代码'),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误信息'),
    sa.Column('retry_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='重试次数'),
    sa.Column('max_retries', mysql.BIGINT(), autoincrement=False, nullable=True, comment='最大重试次数'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'digital_human_tasks', ['user_id'], unique=False)
    op.create_index('idx_status', 'digital_human_tasks', ['status', 'priority'], unique=False)
    op.create_index('idx_digital_human_id', 'digital_human_tasks', ['digital_human_id'], unique=False)
    op.create_index('idx_created_at', 'digital_human_tasks', ['created_at'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('notify_task_complete', mysql.ENUM('0', '1'), nullable=True, comment='任务完成通知'),
    sa.Column('notify_task_failed', mysql.ENUM('0', '1'), nullable=True, comment='任务失败通知'),
    sa.Column('notify_review_result', mysql.ENUM('0', '1'), nullable=True, comment='审核结果通知'),
    sa.Column('notify_system', mysql.ENUM('0', '1'), nullable=True, comment='系统公告通知'),
    sa.Column('email_enabled', mysql.ENUM('0', '1'), nullable=True, comment='邮件通知总开关'),
    sa.Column('email_task_complete', mysql.ENUM('0', '1'), nullable=True, comment='任务完成(邮件)'),
    sa.Column('email_task_failed', mysql.ENUM('0', '1'), nullable=True, comment='任务失败(邮件)'),
    sa.Column('email_payment', mysql.ENUM('0', '1'), nullable=True, comment='支付相关(邮件)'),
    sa.Column('email_security', mysql.ENUM('0', '1'), nullable=True, comment='安全相关(邮件)'),
    sa.Column('sms_enabled', mysql.ENUM('0', '1'), nullable=True, comment='短信通知总开关'),
    sa.Column('sms_payment', mysql.ENUM('0', '1'), nullable=True, comment='支付相关(短信)'),
    sa.Column('sms_security', mysql.ENUM('0', '1'), nullable=True, comment='安全相关(短信)'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'user_notification_settings', ['user_id'], unique=False)
    op.create_index('idx_user_id', 'user_notification_settings', ['user_id'], unique=False)
    op.create_table('user_memberships',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('membership_type', mysql.ENUM('basic', 'pro', 'enterprise'), nullable=False, comment='会员类型'),
    sa.Column('original_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='原价'),
    sa.Column('actual_price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='实付金额'),
    sa.Column('payment_method', mysql.ENUM('alipay', 'wechat', 'stripe', 'wallet', 'coupon'), nullable=True, comment='支付方式'),
    sa.Column('order_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='订单号'),
    sa.Column('start_at', mysql.DATETIME(), nullable=False, comment='开始时间'),
    sa.Column('end_at', mysql.DATETIME(), nullable=False, comment='结束时间'),
    sa.Column('auto_renew', mysql.ENUM('0', '1'), nullable=True, comment='是否自动续费'),
    sa.Column('coupon_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用的优惠券ID'),
    sa.Column('discount_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='优惠金额'),
    sa.Column('status', mysql.ENUM('pending', 'paid', 'cancelled', 'expired', 'refund'), nullable=True, comment='订单状态'),
    sa.Column('paid_at', mysql.DATETIME(), nullable=True, comment='支付时间'),
    sa.Column('refund_at', mysql.DATETIME(), nullable=True, comment='退款时间'),
    sa.Column('refund_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='退款金额'),
    sa.Column('refund_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='退款原因'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('order_no', 'user_memberships', ['order_no'], unique=False)
    op.create_index('idx_user_id', 'user_memberships', ['user_id'], unique=False)
    op.create_index('idx_status_time', 'user_memberships', ['status', 'created_at'], unique=False)
    op.create_index('idx_order_no', 'user_memberships', ['order_no'], unique=False)
    op.create_index('idx_end_at', 'user_memberships', ['end_at'], unique=False)
    op.create_table('user_messages',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('message_type', mysql.ENUM('system', 'task_complete', 'task_failed', 'review_result', 'payment', 'security', 'other'), nullable=False, comment='消息类型'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='内容'),
    sa.Column('action_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='跳转链接'),
    sa.Column('action_text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='链接文字'),
    sa.Column('related_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='关联类型'),
    sa.Column('related_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联ID'),
    sa.Column('is_read', mysql.ENUM('0', '1'), nullable=True, comment='是否已读'),
    sa.Column('read_at', mysql.DATETIME(), nullable=True, comment='阅读时间'),
    sa.Column('push_sent', mysql.ENUM('0', '1'), nullable=True, comment='是否已推送'),
    sa.Column('email_sent', mysql.ENUM('0', '1'), nullable=True, comment='是否已发送邮件'),
    sa.Column('sms_sent', mysql.ENUM('0', '1'), nullable=True, comment='是否已发送短信'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id_read', 'user_messages', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_type', 'user_messages', ['message_type'], unique=False)
    op.create_index('idx_created_at', 'user_messages', ['created_at'], unique=False)
    op.create_table('video_outputs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='项目ID'),
    sa.Column('video_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='视频文件URL'),
    sa.Column('video_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='视频存储路径'),
    sa.Column('thumbnail_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='缩略图URL'),
    sa.Column('video_file_size', mysql.BIGINT(), autoincrement=False, nullable=True, comment='视频文件大小'),
    sa.Column('resolution', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='分辨率'),
    sa.Column('duration', mysql.DECIMAL(precision=8, scale=2), nullable=True, comment='实际时长(秒)'),
    sa.Column('fps', mysql.BIGINT(), autoincrement=False, nullable=True, comment='帧率'),
    sa.Column('codec', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='编码'),
    sa.Column('bitrate', mysql.BIGINT(), autoincrement=False, nullable=True, comment='码率'),
    sa.Column('has_audio', mysql.ENUM('0', '1'), nullable=True, comment='是否有音频'),
    sa.Column('quality_score', mysql.BIGINT(), autoincrement=False, nullable=True, comment='质量评分'),
    sa.Column('review_status', mysql.ENUM('pending', 'approved', 'rejected', 'auto_approved', 'auto_rejected'), nullable=True, comment='审核状态'),
    sa.Column('review_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='审核原因'),
    sa.Column('watermark_embedded', mysql.ENUM('0', '1'), nullable=True, comment='是否嵌入水印'),
    sa.Column('c2pa_manifest_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='C2PA清单文件URL'),
    sa.Column('share_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='分享Token'),
    sa.Column('share_enabled', mysql.ENUM('0', '1'), nullable=True, comment='是否启用分享'),
    sa.Column('share_expire_at', mysql.DATETIME(), nullable=True, comment='分享过期时间'),
    sa.Column('share_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='分享密码'),
    sa.Column('view_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='查看次数'),
    sa.Column('download_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='下载次数'),
    sa.Column('share_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='分享次数'),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True, comment='过期时间'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('project_id', 'video_outputs', ['project_id'], unique=False)
    op.create_index('idx_review_status', 'video_outputs', ['review_status'], unique=False)
    op.create_index('idx_created_at', 'video_outputs', ['created_at'], unique=False)
    op.create_table('coupons',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='优惠券名称'),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='描述'),
    sa.Column('coupon_type', mysql.ENUM('fixed', 'percent', 'free_days'), nullable=False, comment='类型'),
    sa.Column('value', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='优惠值'),
    sa.Column('min_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低使用金额'),
    sa.Column('max_use_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='最大使用次数'),
    sa.Column('used_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='已使用次数'),
    sa.Column('user_limit', mysql.BIGINT(), autoincrement=False, nullable=True, comment='每人限领次数'),
    sa.Column('valid_for_days', mysql.BIGINT(), autoincrement=False, nullable=True, comment='领取后有效天数'),
    sa.Column('valid_from', mysql.DATETIME(), nullable=True, comment='有效期开始'),
    sa.Column('valid_to', mysql.DATETIME(), nullable=True, comment='有效期结束'),
    sa.Column('applicable_memberships', mysql.JSON(), nullable=True, comment='适用会员等级'),
    sa.Column('applicable_products', mysql.JSON(), nullable=True, comment='适用商品类型'),
    sa.Column('status', mysql.ENUM('active', 'inactive', 'expired'), nullable=True, comment='状态'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_status', 'coupons', ['status'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('project_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='项目ID'),
    sa.Column('batch_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='批次ID'),
    sa.Column('task_type', mysql.ENUM('tts', 'video_gen', 'postprocess', 'quality_check', 'full_pipeline'), nullable=False, comment='任务类型'),
    sa.Column('status', mysql.ENUM('queued', 'processing', 'completed', 'failed', 'cancelled'), nullable=True, comment='状态'),
    sa.Column('priority', mysql.BIGINT(), autoincrement=False, nullable=True, comment='优先级'),
    sa.Column('queue_position', mysql.BIGINT(), autoincrement=False, nullable=True, comment='队列位置'),
    sa.Column('progress', mysql.BIGINT(), autoincrement=False, nullable=True, comment='进度 0-100'),
    sa.Column('current_step', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='当前步骤'),
    sa.Column('model_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='提供商'),
    sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='模型名称'),
    sa.Column('model_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='模型版本'),
    sa.Column('input_config', mysql.JSON(), nullable=True, comment='输入配置'),
    sa.Column('output_config', mysql.JSON(), nullable=True, comment='输出配置'),
    sa.Column('output_urls', mysql.JSON(), nullable=True, comment='输出文件URLs'),
    sa.Column('estimated_duration', mysql.BIGINT(), autoincrement=False, nullable=True, comment='预估时长(秒)'),
    sa.Column('started_at', mysql.DATETIME(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True, comment='完成时间'),
    sa.Column('duration_seconds', mysql.BIGINT(), autoincrement=False, nullable=True, comment='实际耗时(秒)'),
    sa.Column('cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='成本(分)'),
    sa.Column('retry_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='重试次数'),
    sa.Column('max_retries', mysql.BIGINT(), autoincrement=False, nullable=True, comment='最大重试次数'),
    sa.Column('retry_from_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='上次失败的提供商'),
    sa.Column('fallback_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='切换到的提供商'),
    sa.Column('error_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='错误代码'),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误信息'),
    sa.Column('is_timeout', mysql.ENUM('0', '1'), nullable=True, comment='是否超时'),
    sa.Column('logs', mysql.JSON(), nullable=True, comment='详细日志'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'generation_tasks', ['user_id'], unique=False)
    op.create_index('idx_status_priority', 'generation_tasks', ['status', 'priority'], unique=False)
    op.create_index('idx_project_id', 'generation_tasks', ['project_id'], unique=False)
    op.create_index('idx_created_at', 'generation_tasks', ['created_at'], unique=False)
    op.create_index('idx_batch_id', 'generation_tasks', ['batch_id'], unique=False)
    op.create_table('user_wallets',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('balance', mysql.DECIMAL(precision=12, scale=4), nullable=True, comment='账户余额'),
    sa.Column('frozen_balance', mysql.DECIMAL(precision=12, scale=4), nullable=True, comment='冻结余额'),
    sa.Column('total_recharge', mysql.DECIMAL(precision=12, scale=4), nullable=True, comment='累计充值金额'),
    sa.Column('total_consume', mysql.DECIMAL(precision=12, scale=4), nullable=True, comment='累计消费金额'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'user_wallets', ['user_id'], unique=False)
    op.create_table('user_login_histories',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('login_type', mysql.ENUM('password', 'sms', 'oauth', 'wechat', 'google', 'apple'), nullable=True, comment='登录方式'),
    sa.Column('device_type', mysql.ENUM('web', 'ios', 'android', 'unknown'), nullable=True, comment='设备类型'),
    sa.Column('device_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='设备唯一标识'),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False, comment='IP地址'),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='User-Agent信息'),
    sa.Column('location_country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='国家'),
    sa.Column('location_province', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='省份'),
    sa.Column('location_city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='城市'),
    sa.Column('is_abnormal', mysql.ENUM('0', '1'), nullable=True, comment='是否异常登录'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'user_login_histories', ['user_id'], unique=False)
    op.create_index('idx_ip', 'user_login_histories', ['ip_address'], unique=False)
    op.create_index('idx_created_at', 'user_login_histories', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='手机号'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='邮箱'),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='昵称'),
    sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='头像URL'),
    sa.Column('bio', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='个人简介'),
    sa.Column('real_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='真实姓名'),
    sa.Column('id_card_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=18), nullable=True, comment='身份证号'),
    sa.Column('real_name_verified', mysql.ENUM('0', '1'), nullable=True, comment='实名认证状态'),
    sa.Column('membership_type', mysql.ENUM('free', 'basic', 'pro', 'enterprise'), nullable=True, comment='会员类型'),
    sa.Column('membership_expire_at', mysql.DATETIME(), nullable=True, comment='会员到期时间'),
    sa.Column('quota_digital_human', mysql.BIGINT(), autoincrement=False, nullable=True, comment='数字人配额'),
    sa.Column('quota_video_monthly', mysql.BIGINT(), autoincrement=False, nullable=True, comment='每月视频生成次数配额'),
    sa.Column('quota_video_max_duration', mysql.BIGINT(), autoincrement=False, nullable=True, comment='单视频最长时长(秒)'),
    sa.Column('quota_storage_mb', mysql.BIGINT(), autoincrement=False, nullable=True, comment='存储空间配额(MB)'),
    sa.Column('status', mysql.ENUM('active', 'suspended', 'deleted'), nullable=True, comment='账号状态'),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True, comment='最后登录IP'),
    sa.Column('register_ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True, comment='注册IP'),
    sa.Column('register_source', mysql.ENUM('web', 'mobile', 'wechat', 'google', 'apple'), nullable=True, comment='注册来源'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('phone', 'users', ['phone'], unique=False)
    op.create_index('idx_status', 'users', ['status'], unique=False)
    op.create_index('idx_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_membership', 'users', ['membership_type', 'membership_expire_at'], unique=False)
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_created_at', 'users', ['created_at'], unique=False)
    op.create_index('email', 'users', ['email'], unique=False)
    op.create_table('platform_assets',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('asset_type', mysql.ENUM('background', 'bgm', 'transition', 'sticker', 'subtitle_style', 'particle_effect'), nullable=False, comment='素材类型'),
    sa.Column('original_filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='文件URL'),
    sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='文件存储路径'),
    sa.Column('file_size', mysql.BIGINT(), autoincrement=False, nullable=True, comment='文件大小(字节)'),
    sa.Column('width', mysql.BIGINT(), autoincrement=False, nullable=True, comment='宽度'),
    sa.Column('height', mysql.BIGINT(), autoincrement=False, nullable=True, comment='高度'),
    sa.Column('duration', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='时长'),
    sa.Column('fps', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='帧率'),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='分类'),
    sa.Column('subcategory', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='子分类'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签'),
    sa.Column('license_type', mysql.ENUM('free', 'premium', 'exclusive'), nullable=True, comment='授权类型'),
    sa.Column('membership_required', mysql.ENUM('free', 'all', 'basic', 'pro', 'enterprise'), nullable=True, comment='会员等级要求'),
    sa.Column('usage_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用次数'),
    sa.Column('view_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='查看次数'),
    sa.Column('status', mysql.ENUM('active', 'inactive', 'deleted'), nullable=True, comment='状态'),
    sa.Column('uploader_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='上传者ID'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_usage_count', 'platform_assets', ['usage_count'], unique=False)
    op.create_index('idx_type', 'platform_assets', ['asset_type'], unique=False)
    op.create_index('idx_status', 'platform_assets', ['status'], unique=False)
    op.create_index('idx_license', 'platform_assets', ['license_type', 'membership_required'], unique=False)
    op.create_index('idx_category', 'platform_assets', ['category'], unique=False)
    op.create_table('admin_operation_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='管理员ID'),
    sa.Column('admin_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='管理员用户名'),
    sa.Column('action', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='操作'),
    sa.Column('module', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='模块'),
    sa.Column('operation_type', mysql.ENUM('create', 'update', 'delete', 'view', 'approve', 'reject', 'other'), nullable=False, comment='操作类型'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='操作描述'),
    sa.Column('target_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='目标类型'),
    sa.Column('target_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='目标ID'),
    sa.Column('before_data', mysql.JSON(), nullable=True, comment='变更前数据'),
    sa.Column('after_data', mysql.JSON(), nullable=True, comment='变更后数据'),
    sa.Column('changed_fields', mysql.JSON(), nullable=True, comment='变更字段列表'),
    sa.Column('request_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='请求方法'),
    sa.Column('request_uri', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='请求URI'),
    sa.Column('request_params', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='请求参数'),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='User-Agent'),
    sa.Column('result', mysql.ENUM('success', 'failed'), nullable=False, comment='结果'),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误信息'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_target', 'admin_operation_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_created_at', 'admin_operation_logs', ['created_at'], unique=False)
    op.create_index('idx_admin_id', 'admin_operation_logs', ['admin_id'], unique=False)
    op.create_index('idx_action', 'admin_operation_logs', ['action'], unique=False)
    op.create_table('model_usage_statistics',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.DATE(), nullable=False, comment='统计日期'),
    sa.Column('stat_hour', mysql.BIGINT(), autoincrement=False, nullable=True, comment='统计小时'),
    sa.Column('model_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='提供商'),
    sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='模型名称'),
    sa.Column('model_task_type', mysql.ENUM('digital_human', 'video_gen', 'tts', 'ai_writing'), nullable=False, comment='任务类型'),
    sa.Column('call_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='调用次数'),
    sa.Column('success_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='成功次数'),
    sa.Column('fail_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='失败次数'),
    sa.Column('timeout_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='超时次数'),
    sa.Column('avg_duration_ms', mysql.BIGINT(), autoincrement=False, nullable=True, comment='平均耗时(毫秒)'),
    sa.Column('p50_duration_ms', mysql.BIGINT(), autoincrement=False, nullable=True, comment='P50耗时'),
    sa.Column('p95_duration_ms', mysql.BIGINT(), autoincrement=False, nullable=True, comment='P95耗时'),
    sa.Column('p99_duration_ms', mysql.BIGINT(), autoincrement=False, nullable=True, comment='P99耗时'),
    sa.Column('total_cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='总成本(分)'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_stat_date', 'model_usage_statistics', ['stat_date'], unique=False)
    op.create_index('idx_date_provider_model', 'model_usage_statistics', ['stat_date', 'stat_hour', 'model_provider', 'model_name', 'model_task_type'], unique=False)
    op.create_table('user_coupons',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('coupon_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='优惠券ID'),
    sa.Column('coupon_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='券码'),
    sa.Column('status', mysql.ENUM('unused', 'used', 'expired', 'invalid'), nullable=True, comment='状态'),
    sa.Column('used_at', mysql.DATETIME(), nullable=True, comment='使用时间'),
    sa.Column('used_order_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='使用订单号'),
    sa.Column('valid_from', mysql.DATETIME(), nullable=False, comment='有效期开始'),
    sa.Column('valid_to', mysql.DATETIME(), nullable=False, comment='有效期结束'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'user_coupons', ['user_id'], unique=False)
    op.create_index('idx_status_time', 'user_coupons', ['status', 'valid_to'], unique=False)
    op.create_index('idx_coupon_id', 'user_coupons', ['coupon_id'], unique=False)
    op.create_index('coupon_code', 'user_coupons', ['coupon_code'], unique=False)
    op.create_table('script_templates',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='模板名称'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='模板描述'),
    sa.Column('cover_image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='封面图URL'),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='分类'),
    sa.Column('subcategory', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='子分类'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签'),
    sa.Column('content', mysql.JSON(), nullable=False, comment='模板内容结构'),
    sa.Column('example_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='示例文本'),
    sa.Column('prompt_template', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='AI生成提示词模板'),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='支持语言'),
    sa.Column('input_fields', mysql.JSON(), nullable=True, comment='需要的输入字段'),
    sa.Column('source', mysql.ENUM('platform', 'user', 'market'), nullable=True, comment='来源'),
    sa.Column('creator_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建者ID'),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='价格'),
    sa.Column('usage_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用次数'),
    sa.Column('favor_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='收藏次数'),
    sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), nullable=True, comment='评分'),
    sa.Column('rating_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='评分人数'),
    sa.Column('status', mysql.ENUM('active', 'inactive', 'deleted'), nullable=True, comment='状态'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_usage_count', 'script_templates', ['usage_count'], unique=False)
    op.create_index('idx_status', 'script_templates', ['status'], unique=False)
    op.create_index('idx_source', 'script_templates', ['source'], unique=False)
    op.create_index('idx_category', 'script_templates', ['category'], unique=False)
    op.create_table('user_wallet_transactions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('transaction_no', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='交易流水号'),
    sa.Column('transaction_type', mysql.ENUM('recharge', 'consume', 'refund', 'recharge_refund', 'invite_reward', 'admin_adjust'), nullable=False, comment='交易类型'),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=4), nullable=False, comment='交易金额'),
    sa.Column('balance_before', mysql.DECIMAL(precision=12, scale=4), nullable=False, comment='交易前余额'),
    sa.Column('balance_after', mysql.DECIMAL(precision=12, scale=4), nullable=False, comment='交易后余额'),
    sa.Column('related_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='关联类型'),
    sa.Column('related_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联ID'),
    sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('transaction_no', 'user_wallet_transactions', ['transaction_no'], unique=False)
    op.create_index('idx_user_id', 'user_wallet_transactions', ['user_id'], unique=False)
    op.create_index('idx_type_time', 'user_wallet_transactions', ['transaction_type', 'created_at'], unique=False)
    op.create_index('idx_transaction_no', 'user_wallet_transactions', ['transaction_no'], unique=False)
    op.create_table('scripts',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='脚本标题'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='脚本描述'),
    sa.Column('content', mysql.JSON(), nullable=False, comment='脚本内容'),
    sa.Column('plain_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='纯文本内容'),
    sa.Column('word_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='字数'),
    sa.Column('estimated_duration', mysql.DECIMAL(precision=8, scale=2), nullable=True, comment='预估时长(秒)'),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='主要语言'),
    sa.Column('voice_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联音色ID'),
    sa.Column('base_tts_speed', mysql.DECIMAL(precision=3, scale=2), nullable=True, comment='基础语速'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签'),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='分类'),
    sa.Column('template_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='来源模板ID'),
    sa.Column('is_template', mysql.ENUM('0', '1'), nullable=True, comment='是否为模板'),
    sa.Column('ai_generated', mysql.ENUM('0', '1'), nullable=True, comment='是否AI生成'),
    sa.Column('ai_prompt', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='AI生成时的提示词'),
    sa.Column('ai_model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='使用的AI模型'),
    sa.Column('status', mysql.ENUM('draft', 'published', 'archived'), nullable=True, comment='状态'),
    sa.Column('usage_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用次数'),
    sa.Column('view_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='查看次数'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'scripts', ['user_id'], unique=False)
    op.create_index('idx_status', 'scripts', ['status'], unique=False)
    op.create_index('idx_is_template', 'scripts', ['is_template'], unique=False)
    op.create_index('idx_category', 'scripts', ['category'], unique=False)
    op.create_table('user_assets',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('asset_type', mysql.ENUM('image', 'video', 'audio', 'font', 'subtitle_style'), nullable=False, comment='素材类型'),
    sa.Column('original_filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='文件URL'),
    sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='文件存储路径'),
    sa.Column('file_size', mysql.BIGINT(), autoincrement=False, nullable=False, comment='文件大小(字节)'),
    sa.Column('width', mysql.BIGINT(), autoincrement=False, nullable=True, comment='宽度'),
    sa.Column('height', mysql.BIGINT(), autoincrement=False, nullable=True, comment='高度'),
    sa.Column('duration', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='时长'),
    sa.Column('fps', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='帧率'),
    sa.Column('audio_channels', mysql.BIGINT(), autoincrement=False, nullable=True, comment='声道数'),
    sa.Column('codec', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='编码格式'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='素材名称'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='描述'),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='分类'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签'),
    sa.Column('color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='主色调'),
    sa.Column('usage_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用次数'),
    sa.Column('status', mysql.ENUM('uploading', 'processing', 'ready', 'failed'), nullable=True, comment='状态'),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误信息'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'user_assets', ['user_id'], unique=False)
    op.create_index('idx_type', 'user_assets', ['asset_type'], unique=False)
    op.create_index('idx_status', 'user_assets', ['status'], unique=False)
    op.create_index('idx_created_at', 'user_assets', ['created_at'], unique=False)
    op.create_index('idx_category', 'user_assets', ['category'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('device_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='设备唯一标识'),
    sa.Column('device_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='设备名称'),
    sa.Column('device_type', mysql.ENUM('web', 'ios', 'android', 'desktop'), nullable=True, comment='设备类型'),
    sa.Column('os_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='系统版本'),
    sa.Column('app_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='App版本'),
    sa.Column('last_active_at', mysql.DATETIME(), nullable=True, comment='最后活跃时间'),
    sa.Column('is_active', mysql.ENUM('0', '1'), nullable=True, comment='是否活跃'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'user_devices', ['user_id'], unique=False)
    op.create_table('digital_humans',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='数字人名称'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='描述'),
    sa.Column('source_type', mysql.ENUM('single_photo', 'multi_photos', 'video'), nullable=True, comment='源类型'),
    sa.Column('source_photos', mysql.JSON(), nullable=True, comment='源照片信息'),
    sa.Column('photo_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='照片数量'),
    sa.Column('gender', mysql.ENUM('male', 'female', 'unknown'), nullable=True, comment='性别'),
    sa.Column('age_group', mysql.ENUM('child', 'young', 'middle', 'senior'), nullable=True, comment='年龄段'),
    sa.Column('skin_tone', mysql.ENUM('light', 'medium', 'dark'), nullable=True, comment='肤色'),
    sa.Column('hairstyle_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='发型配置ID'),
    sa.Column('clothing_type', mysql.ENUM('business', 'casual', 'formal', 'custom'), nullable=True, comment='服装类型'),
    sa.Column('clothing_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='自定义服装图URL'),
    sa.Column('accessories', mysql.JSON(), nullable=True, comment='配饰'),
    sa.Column('background_type', mysql.ENUM('transparent', 'color', 'scene', 'custom'), nullable=True, comment='背景类型'),
    sa.Column('background_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='背景值'),
    sa.Column('status', mysql.ENUM('pending', 'processing', 'completed', 'failed', 'deleted'), nullable=True, comment='生成状态'),
    sa.Column('model_version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='模型版本'),
    sa.Column('model_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='模型提供商'),
    sa.Column('model_file_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='数字人模型文件URL'),
    sa.Column('preview_image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='静态预览图URL'),
    sa.Column('preview_video_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='动态预览视频URL'),
    sa.Column('preview_video_duration', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='预览视频时长(秒)'),
    sa.Column('authorization_type', mysql.ENUM('self', 'others', 'public'), nullable=False, comment='授权类型'),
    sa.Column('authorization_status', mysql.ENUM('auto_approved', 'pending', 'approved', 'rejected'), nullable=True, comment='授权审核状态'),
    sa.Column('authorization_proof_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='授权证明文件URL'),
    sa.Column('authorization_reject_reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='驳回原因'),
    sa.Column('authorization_expire_at', mysql.DATETIME(), nullable=True, comment='授权到期时间'),
    sa.Column('usage_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用次数'),
    sa.Column('is_default', mysql.ENUM('0', '1'), nullable=True, comment='是否为默认数字人'),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='父版本ID'),
    sa.Column('version_number', mysql.BIGINT(), autoincrement=False, nullable=True, comment='版本号'),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='生成失败原因'),
    sa.Column('retry_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='重试次数'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'digital_humans', ['user_id'], unique=False)
    op.create_index('idx_usage_count', 'digital_humans', ['usage_count'], unique=False)
    op.create_index('idx_status', 'digital_humans', ['status'], unique=False)
    op.create_index('idx_authorization', 'digital_humans', ['authorization_type', 'authorization_status'], unique=False)
    op.create_table('tts_audio_files',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('project_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='项目ID'),
    sa.Column('script_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='脚本ID'),
    sa.Column('task_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='生成任务ID'),
    sa.Column('voice_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='音色ID'),
    sa.Column('text_content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='文本内容'),
    sa.Column('voice_config', mysql.JSON(), nullable=True, comment='语音配置'),
    sa.Column('audio_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='音频文件URL'),
    sa.Column('audio_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='音频存储路径'),
    sa.Column('file_size', mysql.BIGINT(), autoincrement=False, nullable=True, comment='文件大小(字节)'),
    sa.Column('duration', mysql.DECIMAL(precision=8, scale=2), nullable=True, comment='时长(秒)'),
    sa.Column('format', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='格式'),
    sa.Column('sample_rate', mysql.BIGINT(), autoincrement=False, nullable=True, comment='采样率'),
    sa.Column('tts_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='TTS提供商'),
    sa.Column('tts_model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='TTS模型'),
    sa.Column('cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='成本(分)'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_voice_id', 'tts_audio_files', ['voice_id'], unique=False)
    op.create_index('idx_user_id', 'tts_audio_files', ['user_id'], unique=False)
    op.create_index('idx_project_id', 'tts_audio_files', ['project_id'], unique=False)
    op.create_table('ai_writing_tasks',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('script_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联脚本ID'),
    sa.Column('task_type', mysql.ENUM('generate', 'rewrite', 'expand', 'shrink', 'translate', 'polish'), nullable=False, comment='任务类型'),
    sa.Column('input_prompt', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='提示词'),
    sa.Column('input_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='输入文本'),
    sa.Column('source_language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='源语言'),
    sa.Column('target_language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='目标语言'),
    sa.Column('template_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用的模板ID'),
    sa.Column('output_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='生成的内容'),
    sa.Column('output_segments', mysql.JSON(), nullable=True, comment='分段后的内容'),
    sa.Column('status', mysql.ENUM('queued', 'processing', 'completed', 'failed'), nullable=True, comment='状态'),
    sa.Column('progress', mysql.BIGINT(), autoincrement=False, nullable=True, comment='进度 0-100'),
    sa.Column('ai_model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='使用的AI模型'),
    sa.Column('emotion', mysql.ENUM('neutral', 'happy', 'serious', 'humorous'), nullable=True, comment='情感倾向'),
    sa.Column('style', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='风格'),
    sa.Column('input_tokens', mysql.BIGINT(), autoincrement=False, nullable=True, comment='输入token数'),
    sa.Column('output_tokens', mysql.BIGINT(), autoincrement=False, nullable=True, comment='输出token数'),
    sa.Column('cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='成本(分)'),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误信息'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'ai_writing_tasks', ['user_id'], unique=False)
    op.create_index('idx_status', 'ai_writing_tasks', ['status'], unique=False)
    op.create_index('idx_script_id', 'ai_writing_tasks', ['script_id'], unique=False)
    op.create_table('asset_categories',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='分类名称'),
    sa.Column('name_en', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='英文名称'),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='图标'),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='父分类ID'),
    sa.Column('level', mysql.BIGINT(), autoincrement=False, nullable=True, comment='层级'),
    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='路径串'),
    sa.Column('asset_types', mysql.JSON(), nullable=True, comment='适用素材类型'),
    sa.Column('sort_order', mysql.BIGINT(), autoincrement=False, nullable=True, comment='排序序号'),
    sa.Column('status', mysql.ENUM('active', 'inactive'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_status', 'asset_categories', ['status'], unique=False)
    op.create_index('idx_parent', 'asset_categories', ['parent_id'], unique=False)
    op.create_index('idx_level', 'asset_categories', ['level'], unique=False)
    op.create_table('admins',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='密码哈希'),
    sa.Column('real_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='真实姓名'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='手机号'),
    sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='头像'),
    sa.Column('role', mysql.ENUM('super_admin', 'admin', 'content_reviewer', 'operator', 'viewer'), nullable=False, comment='角色'),
    sa.Column('permissions', mysql.JSON(), nullable=True, comment='权限列表'),
    sa.Column('status', mysql.ENUM('active', 'suspended', 'deleted'), nullable=True, comment='状态'),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True, comment='最后登录IP'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'admins', ['username'], unique=False)
    op.create_index('idx_status', 'admins', ['status'], unique=False)
    op.create_index('idx_role', 'admins', ['role'], unique=False)
    op.create_index('email', 'admins', ['email'], unique=False)
    op.create_table('platform_statistics',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.DATE(), nullable=False, comment='统计日期'),
    sa.Column('stat_hour', mysql.BIGINT(), autoincrement=False, nullable=True, comment='统计小时'),
    sa.Column('new_users', mysql.BIGINT(), autoincrement=False, nullable=True, comment='新增用户'),
    sa.Column('active_users', mysql.BIGINT(), autoincrement=False, nullable=True, comment='活跃用户'),
    sa.Column('paid_users', mysql.BIGINT(), autoincrement=False, nullable=True, comment='付费用户'),
    sa.Column('churned_users', mysql.BIGINT(), autoincrement=False, nullable=True, comment='流失用户'),
    sa.Column('video_projects_created', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建项目数'),
    sa.Column('video_projects_completed', mysql.BIGINT(), autoincrement=False, nullable=True, comment='完成项目数'),
    sa.Column('video_projects_failed', mysql.BIGINT(), autoincrement=False, nullable=True, comment='失败项目数'),
    sa.Column('video_total_duration', mysql.BIGINT(), autoincrement=False, nullable=True, comment='总视频时长(秒)'),
    sa.Column('digital_humans_created', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建数字人数'),
    sa.Column('ai_tasks_submitted', mysql.BIGINT(), autoincrement=False, nullable=True, comment='提交AI任务数'),
    sa.Column('ai_tasks_completed', mysql.BIGINT(), autoincrement=False, nullable=True, comment='完成AI任务数'),
    sa.Column('total_revenue_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='总收入(分)'),
    sa.Column('membership_revenue_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='会员收入(分)'),
    sa.Column('single_purchase_revenue_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='单次购买收入(分)'),
    sa.Column('total_cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='总成本(分)'),
    sa.Column('model_cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='AI模型成本(分)'),
    sa.Column('storage_cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='存储成本(分)'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_stat_date', 'platform_statistics', ['stat_date'], unique=False)
    op.create_index('idx_date_hour', 'platform_statistics', ['stat_date', 'stat_hour'], unique=False)
    op.create_table('video_projects',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('project_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='项目名称'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='项目描述'),
    sa.Column('resolution', mysql.ENUM('720p', '1080p', '2k', '4k'), nullable=True, comment='分辨率'),
    sa.Column('aspect_ratio', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='宽高比'),
    sa.Column('fps', mysql.BIGINT(), autoincrement=False, nullable=True, comment='帧率'),
    sa.Column('max_duration', mysql.BIGINT(), autoincrement=False, nullable=True, comment='最大时长(秒)'),
    sa.Column('digital_human_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='主数字人ID'),
    sa.Column('digital_human_config', mysql.JSON(), nullable=True, comment='数字人配置'),
    sa.Column('script_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='脚本ID'),
    sa.Column('script_content', mysql.JSON(), nullable=True, comment='脚本内容快照'),
    sa.Column('voice_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='TTS音色ID'),
    sa.Column('tts_config', mysql.JSON(), nullable=True, comment='TTS配置'),
    sa.Column('background_asset_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='背景素材ID'),
    sa.Column('background_type', mysql.ENUM('color', 'image', 'video', 'transparent'), nullable=True, comment='背景类型'),
    sa.Column('background_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='背景值'),
    sa.Column('bgm_asset_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='背景音乐素材ID'),
    sa.Column('bgm_volume', mysql.DECIMAL(precision=3, scale=2), nullable=True, comment='BGM音量'),
    sa.Column('timeline_config', mysql.JSON(), nullable=True, comment='时间线配置'),
    sa.Column('subtitle_config', mysql.JSON(), nullable=True, comment='字幕配置'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签'),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='分类'),
    sa.Column('generation_status', mysql.ENUM('draft', 'queued', 'preprocessing', 'generating', 'postprocessing', 'quality_check', 'completed', 'failed'), nullable=True, comment='生成状态'),
    sa.Column('model_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='模型提供商'),
    sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='模型名称'),
    sa.Column('priority', mysql.BIGINT(), autoincrement=False, nullable=True, comment='优先级'),
    sa.Column('view_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='查看次数'),
    sa.Column('download_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='下载次数'),
    sa.Column('share_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='分享次数'),
    sa.Column('cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='实际成本(分)'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='软删除时间'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'video_projects', ['user_id'], unique=False)
    op.create_index('idx_status_time', 'video_projects', ['generation_status', 'created_at'], unique=False)
    op.create_index('idx_script', 'video_projects', ['script_id'], unique=False)
    op.create_index('idx_digital_human', 'video_projects', ['digital_human_id'], unique=False)
    op.create_index('idx_created_at', 'video_projects', ['created_at'], unique=False)
    op.create_table('voice_clones',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('digital_human_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联数字人ID'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='音色名称'),
    sa.Column('source_audio_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='源音频文件URL'),
    sa.Column('source_duration', mysql.DECIMAL(precision=6, scale=2), nullable=True, comment='源音频时长(秒)'),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='语言'),
    sa.Column('status', mysql.ENUM('pending', 'processing', 'completed', 'failed'), nullable=True, comment='生成状态'),
    sa.Column('model_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='TTS提供商'),
    sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='TTS模型'),
    sa.Column('voice_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='TTS平台返回的音色ID'),
    sa.Column('sample_audio_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='示例音频URL'),
    sa.Column('gender', mysql.ENUM('male', 'female', 'neutral'), nullable=True, comment='性别'),
    sa.Column('age_group', mysql.ENUM('young', 'middle', 'senior'), nullable=True, comment='年龄段'),
    sa.Column('emotion', mysql.ENUM('neutral', 'happy', 'sad', 'angry'), nullable=True, comment='情感倾向'),
    sa.Column('usage_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用次数'),
    sa.Column('is_default', mysql.ENUM('0', '1'), nullable=True, comment='是否为默认音色'),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='错误信息'),
    sa.Column('retry_count', mysql.BIGINT(), autoincrement=False, nullable=True, comment='重试次数'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'voice_clones', ['user_id'], unique=False)
    op.create_index('idx_status', 'voice_clones', ['status'], unique=False)
    op.create_index('idx_digital_human_id', 'voice_clones', ['digital_human_id'], unique=False)
    op.create_table('user_statistics',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('stat_date', sa.DATE(), nullable=False, comment='统计日期'),
    sa.Column('stat_type', mysql.ENUM('daily', 'weekly', 'monthly'), nullable=False, comment='统计类型'),
    sa.Column('video_projects_created', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建项目数'),
    sa.Column('video_projects_completed', mysql.BIGINT(), autoincrement=False, nullable=True, comment='完成项目数'),
    sa.Column('video_projects_failed', mysql.BIGINT(), autoincrement=False, nullable=True, comment='失败项目数'),
    sa.Column('video_total_duration', mysql.BIGINT(), autoincrement=False, nullable=True, comment='总视频时长(秒)'),
    sa.Column('digital_humans_created', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建数字人数'),
    sa.Column('digital_humans_used', mysql.BIGINT(), autoincrement=False, nullable=True, comment='使用数字人次数'),
    sa.Column('cost_cents', mysql.BIGINT(), autoincrement=False, nullable=True, comment='总消费(分)'),
    sa.Column('storage_used_mb', mysql.BIGINT(), autoincrement=False, nullable=True, comment='已用存储(MB)'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_date', 'user_statistics', ['user_id', 'stat_date'], unique=False)
    op.create_index('idx_stat_date', 'user_statistics', ['stat_date'], unique=False)
    op.create_table('user_oauth_bindings',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('provider', mysql.ENUM('wechat', 'google', 'apple'), nullable=False, comment='OAuth提供商'),
    sa.Column('provider_user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='第三方平台用户ID'),
    sa.Column('access_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='访问令牌'),
    sa.Column('refresh_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='刷新令牌'),
    sa.Column('token_expire_at', mysql.DATETIME(), nullable=True, comment='令牌过期时间'),
    sa.Column('union_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='开放平台统一ID'),
    sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='第三方头像'),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='第三方昵称'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_id', 'user_oauth_bindings', ['user_id'], unique=False)
    # ### end Alembic commands ###
