"""add_extensions_tables

Revision ID: cd5141a92311
Revises: 176977ce3821
Create Date: 2026-05-15 18:59:00.870351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5141a92311'
down_revision: Union[str, None] = '176977ce3821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('order_no', sa.String(length=50), nullable=True, comment='关联订单号'),
    sa.Column('consumption_type', sa.Enum('video_gen', 'tts', 'digital_human', 'storage', 'api_call', 'other'), nullable=False, comment='消费类型'),
    sa.Column('resource_id', sa.BigInteger(), nullable=True, comment='资源ID(如视频项目ID)'),
    sa.Column('resource_name', sa.String(length=200), nullable=True, comment='资源名称'),
    sa.Column('quantity', sa.BigInteger(), nullable=True, comment='数量'),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='单价'),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='总金额'),
    sa.Column('before_balance', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='消费前余额'),
    sa.Column('after_balance', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='消费后余额'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='服务提供商'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='模型名称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumption_type', 'consumption_records', ['consumption_type'], unique=False)
    op.create_index('idx_created_at', 'consumption_records', ['created_at'], unique=False)
    op.create_index('idx_user_id', 'consumption_records', ['user_id'], unique=False)
    op.create_table('membership_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_type', sa.Enum('free', 'basic', 'pro', 'enterprise'), nullable=False, comment='计划类型'),
    sa.Column('plan_name', sa.String(length=50), nullable=False, comment='计划名称'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='价格(月)'),
    sa.Column('annual_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='年付价格'),
    sa.Column('discount_percent', sa.BigInteger(), nullable=True, comment='年付折扣百分比'),
    sa.Column('quota_digital_human', sa.BigInteger(), nullable=True, comment='数字人配额'),
    sa.Column('quota_video_monthly', sa.BigInteger(), nullable=True, comment='每月视频生成次数配额'),
    sa.Column('quota_video_max_duration', sa.BigInteger(), nullable=True, comment='单视频最长时长(秒)'),
    sa.Column('quota_storage_mb', sa.BigInteger(), nullable=True, comment='存储空间配额(MB)'),
    sa.Column('quota_api_calls', sa.BigInteger(), nullable=True, comment='API调用配额(每月)'),
    sa.Column('features', sa.JSON(), nullable=True, comment='功能列表'),
    sa.Column('sort_order', sa.BigInteger(), nullable=True, comment='排序顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_type')
    )
    op.create_index('idx_is_active', 'membership_plans', ['is_active'], unique=False)
    op.create_index('idx_plan_type', 'membership_plans', ['plan_type'], unique=False)
    op.create_table('sensitive_words',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False, comment='敏感词'),
    sa.Column('word_type', sa.Enum('politics', 'porn', 'violence', 'crime', 'custom'), nullable=False, comment='敏感词类型'),
    sa.Column('severity_level', sa.BigInteger(), nullable=True, comment='严重程度(1-5)'),
    sa.Column('replacement', sa.String(length=50), nullable=True, comment='替换词'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_index('idx_is_active', 'sensitive_words', ['is_active'], unique=False)
    op.create_index('idx_severity', 'sensitive_words', ['severity_level'], unique=False)
    op.create_index('idx_word_type', 'sensitive_words', ['word_type'], unique=False)
    op.create_table('user_violations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('violation_type', sa.Enum('content_violation', 'spam', 'abuse', 'fraud', 'other'), nullable=False, comment='违规类型'),
    sa.Column('violation_level', sa.Enum('warning', 'minor', 'major', 'critical'), nullable=True, comment='违规等级'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='违规对象类型'),
    sa.Column('target_id', sa.BigInteger(), nullable=True, comment='违规对象ID'),
    sa.Column('target_content', sa.Text(), nullable=True, comment='违规内容'),
    sa.Column('description', sa.Text(), nullable=True, comment='违规描述'),
    sa.Column('evidence_urls', sa.JSON(), nullable=True, comment='证据截图URLs'),
    sa.Column('handler_id', sa.BigInteger(), nullable=True, comment='处理员ID'),
    sa.Column('handle_result', sa.Enum('warning', 'delete_content', 'disable_user', 'ban_user'), nullable=False, comment='处理结果'),
    sa.Column('handle_comment', sa.String(length=500), nullable=True, comment='处理备注'),
    sa.Column('status', sa.Enum('pending', 'handled', 'appealed', 'cleared'), nullable=True, comment='状态'),
    sa.Column('appealed_at', sa.DateTime(), nullable=True, comment='申诉时间'),
    sa.Column('appeal_result', sa.String(length=255), nullable=True, comment='申诉结果'),
    sa.Column('cleared_at', sa.DateTime(), nullable=True, comment='解除时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'user_violations', ['created_at'], unique=False)
    op.create_index('idx_status', 'user_violations', ['status'], unique=False)
    op.create_index('idx_user_id', 'user_violations', ['user_id'], unique=False)
    op.create_index('idx_violation_type', 'user_violations', ['violation_type'], unique=False)
    op.create_table('voice_presets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID(Null表示公共预设)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='预设名称'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言'),
    sa.Column('gender', sa.Enum('male', 'female', 'neutral'), nullable=True, comment='性别'),
    sa.Column('age_group', sa.Enum('child', 'young', 'middle', 'senior'), nullable=True, comment='年龄段'),
    sa.Column('emotion', sa.Enum('neutral', 'happy', 'sad', 'angry', 'formal', 'casual'), nullable=True, comment='情感'),
    sa.Column('speed', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='语速'),
    sa.Column('pitch', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='音调'),
    sa.Column('volume', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='音量'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='TTS提供商'),
    sa.Column('provider_voice_id', sa.String(length=100), nullable=True, comment='提供商音色ID'),
    sa.Column('usage_count', sa.BigInteger(), nullable=True, comment='使用次数'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_is_public', 'voice_presets', ['is_public'], unique=False)
    op.create_index('idx_language', 'voice_presets', ['language'], unique=False)
    op.create_index('idx_user_id', 'voice_presets', ['user_id'], unique=False)
    op.create_table('authorization_proofs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('digital_human_id', sa.BigInteger(), nullable=False, comment='数字人ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('proof_type', sa.Enum('id_card', 'company_cert', 'authorization_letter', 'other'), nullable=False, comment='证明类型'),
    sa.Column('proof_url', sa.String(length=500), nullable=False, comment='证明文件URL'),
    sa.Column('proof_number', sa.String(length=100), nullable=True, comment='证明编号(身份证号/营业执照号等)'),
    sa.Column('holder_name', sa.String(length=100), nullable=True, comment='持证人姓名'),
    sa.Column('holder_id_card', sa.String(length=18), nullable=True, comment='持证人身份证号'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=True, comment='审核状态'),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True, comment='审核员ID'),
    sa.Column('review_comment', sa.String(length=500), nullable=True, comment='审核备注'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['digital_human_id'], ['digital_humans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_digital_human_id', 'authorization_proofs', ['digital_human_id'], unique=False)
    op.create_index('idx_status', 'authorization_proofs', ['status'], unique=False)
    op.create_index('idx_user_id', 'authorization_proofs', ['user_id'], unique=False)
    op.create_table('digital_human_photos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('digital_human_id', sa.BigInteger(), nullable=False, comment='数字人ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('photo_url', sa.String(length=500), nullable=False, comment='照片URL'),
    sa.Column('photo_type', sa.Enum('source', 'processed', 'preview', 'result'), nullable=True, comment='照片类型'),
    sa.Column('photo_order', sa.BigInteger(), nullable=True, comment='照片顺序'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('width', sa.BigInteger(), nullable=True, comment='宽度'),
    sa.Column('height', sa.BigInteger(), nullable=True, comment='高度'),
    sa.Column('is_checked', sa.Boolean(), nullable=True, comment='是否审核通过'),
    sa.Column('check_result', sa.Enum('pending', 'approved', 'rejected'), nullable=True, comment='审核结果'),
    sa.Column('check_reason', sa.String(length=255), nullable=True, comment='审核原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['digital_human_id'], ['digital_humans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_digital_human_id', 'digital_human_photos', ['digital_human_id'], unique=False)
    op.create_index('idx_photo_type', 'digital_human_photos', ['photo_type'], unique=False)
    op.create_index('idx_user_id', 'digital_human_photos', ['user_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='订单号'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('order_type', sa.Enum('membership', 'recharge', 'asset', 'other'), nullable=False, comment='订单类型'),
    sa.Column('product_id', sa.BigInteger(), nullable=True, comment='商品ID'),
    sa.Column('product_name', sa.String(length=200), nullable=True, comment='商品名称'),
    sa.Column('original_amount', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='原价'),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='优惠金额'),
    sa.Column('actual_amount', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='实付金额'),
    sa.Column('payment_method', sa.Enum('alipay', 'wechat', 'stripe', 'wallet', 'coupon'), nullable=True, comment='支付方式'),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'cancelled', 'refunded', 'failed'), nullable=True, comment='支付状态'),
    sa.Column('payment_time', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('coupon_id', sa.BigInteger(), nullable=True, comment='使用的优惠券ID'),
    sa.Column('coupon_code', sa.String(length=50), nullable=True, comment='优惠券码'),
    sa.Column('trade_no', sa.String(length=100), nullable=True, comment='第三方交易号'),
    sa.Column('callback_data', sa.JSON(), nullable=True, comment='回调数据'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_created_at', 'payment_orders', ['created_at'], unique=False)
    op.create_index('idx_order_no', 'payment_orders', ['order_no'], unique=False)
    op.create_index('idx_payment_status', 'payment_orders', ['payment_status'], unique=False)
    op.create_index('idx_user_id', 'payment_orders', ['user_id'], unique=False)
    op.create_table('tts_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('text_hash', sa.String(length=64), nullable=False, comment='文本哈希'),
    sa.Column('text_content', sa.Text(), nullable=False, comment='文本内容'),
    sa.Column('voice_id', sa.BigInteger(), nullable=False, comment='音色ID'),
    sa.Column('voice_config', sa.JSON(), nullable=True, comment='语音配置'),
    sa.Column('audio_url', sa.String(length=500), nullable=False, comment='音频URL'),
    sa.Column('audio_path', sa.String(length=500), nullable=True, comment='音频存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('duration', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='时长(秒)'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='TTS提供商'),
    sa.Column('cost_cents', sa.BigInteger(), nullable=True, comment='成本(分)'),
    sa.Column('hit_count', sa.BigInteger(), nullable=True, comment='命中次数'),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True, comment='最后命中时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['voice_id'], ['voice_clones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_text_hash', 'tts_cache', ['text_hash'], unique=False)
    op.create_index('idx_user_id', 'tts_cache', ['user_id'], unique=False)
    op.create_index('idx_voice_id', 'tts_cache', ['voice_id'], unique=False)
    op.create_table('share_access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('share_token', sa.String(length=100), nullable=False, comment='分享Token'),
    sa.Column('video_output_id', sa.BigInteger(), nullable=False, comment='视频输出ID'),
    sa.Column('visitor_ip', sa.String(length=45), nullable=True, comment='访问者IP'),
    sa.Column('visitor_country', sa.String(length=50), nullable=True, comment='国家'),
    sa.Column('visitor_province', sa.String(length=50), nullable=True, comment='省份'),
    sa.Column('visitor_city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('device_type', sa.Enum('web', 'ios', 'android', 'other'), nullable=True, comment='设备类型'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User-Agent'),
    sa.Column('access_count', sa.BigInteger(), nullable=True, comment='访问次数(同一IP/设备累加)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_output_id'], ['video_outputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'share_access_logs', ['created_at'], unique=False)
    op.create_index('idx_share_token', 'share_access_logs', ['share_token'], unique=False)
    op.create_index('idx_video_output_id', 'share_access_logs', ['video_output_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_video_output_id', table_name='share_access_logs')
    op.drop_index('idx_share_token', table_name='share_access_logs')
    op.drop_index('idx_created_at', table_name='share_access_logs')
    op.drop_table('share_access_logs')
    op.drop_index('idx_voice_id', table_name='tts_cache')
    op.drop_index('idx_user_id', table_name='tts_cache')
    op.drop_index('idx_text_hash', table_name='tts_cache')
    op.drop_table('tts_cache')
    op.drop_index('idx_user_id', table_name='payment_orders')
    op.drop_index('idx_payment_status', table_name='payment_orders')
    op.drop_index('idx_order_no', table_name='payment_orders')
    op.drop_index('idx_created_at', table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index('idx_user_id', table_name='digital_human_photos')
    op.drop_index('idx_photo_type', table_name='digital_human_photos')
    op.drop_index('idx_digital_human_id', table_name='digital_human_photos')
    op.drop_table('digital_human_photos')
    op.drop_index('idx_user_id', table_name='authorization_proofs')
    op.drop_index('idx_status', table_name='authorization_proofs')
    op.drop_index('idx_digital_human_id', table_name='authorization_proofs')
    op.drop_table('authorization_proofs')
    op.drop_index('idx_user_id', table_name='voice_presets')
    op.drop_index('idx_language', table_name='voice_presets')
    op.drop_index('idx_is_public', table_name='voice_presets')
    op.drop_table('voice_presets')
    op.drop_index('idx_violation_type', table_name='user_violations')
    op.drop_index('idx_user_id', table_name='user_violations')
    op.drop_index('idx_status', table_name='user_violations')
    op.drop_index('idx_created_at', table_name='user_violations')
    op.drop_table('user_violations')
    op.drop_index('idx_word_type', table_name='sensitive_words')
    op.drop_index('idx_severity', table_name='sensitive_words')
    op.drop_index('idx_is_active', table_name='sensitive_words')
    op.drop_table('sensitive_words')
    op.drop_index('idx_plan_type', table_name='membership_plans')
    op.drop_index('idx_is_active', table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index('idx_user_id', table_name='consumption_records')
    op.drop_index('idx_created_at', table_name='consumption_records')
    op.drop_index('idx_consumption_type', table_name='consumption_records')
    op.drop_table('consumption_records')
    # ### end Alembic commands ###
